services:
  app:
    image: cosmtrek/air:latest
    container_name: "configs-management-app"
    working_dir: /app
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    environment:
      - REST_API_HOST=0.0.0.0 # Set to 0.0.0.0 to be accessible from outside the container
      - REDIS_HOST=redis:6379 # Point to the Redis service defined below since both are in the same Docker network
    entrypoint: air -c ./build/rest/.air.toml
    volumes:
      - ../:/app
    depends_on:
      - redis
    networks:
      - configs_net
    
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - configs_net

volumes:
  redis-data:
    name: "redis-data"

networks:
  configs_net:
    name: configs_net