services:
  app:
    image: cosmtrek/air:latest
    container_name: "configs-management-app"
    working_dir: /app
    ports:
      - "8080:8080"
    entrypoint: air -c ./build/rest/.air.toml
    volumes:
      - ../:/app
    depends_on:
      - redis
    networks:
      - configs_net
    
  redis:
    image: "redis:alpine"
    container_name: "configs-management-redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - configs_net

volumes:
  redis-data:
    name: "configs-management-redis-data"

networks:
  configs_net:
    name: configs_net