version: "3.8"

services:
  redis:
    image: "redis:alpine"
    container_name: "configs-management-redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dev-network

volumes:
  redis-data:
    name: "configs-management-redis-data"

networks:
  dev-network:
    name: "dev-network"